/** Job matching profile — Gowrishankar Sekar */
module.exports = {
  name: 'Gowrishankar Sekar',
  location: 'Chennai, India',
  experienceYears: 11,

  mustHave: [
    'java',
    'spring',
    'backend',
    'microservice',
    'rest',
    'api',
    'aws',
    'software engineer',
    'tech lead',
    'developer',
  ],

  strongPlus: [
    'llm',
    'generative ai',
    'machine learning',
    'ml engineer',
    'ai engineer',
    'python',
    'pytorch',
    'nlp',
    'agentic',
    'mcp',
    'integration',
    'architect',
    'kubernetes',
    'devops',
    'full stack',
    'platform',
    'senior',
    'lead',
  ],

  locationKeywords: [
    'chennai',
    'remote',
    'india',
    'work from home',
    'hybrid',
    'anywhere',
    'wfh',
    'bengaluru',
    'bangalore',
  ],

  negative: [
    'intern',
    'internship',
    'fresher',
    '0-1 year',
    '0 - 1 year',
    'campus hire',
    'new grad',
    'unpaid',
    'volunteer',
  ],

  tier1Titles: [
    'senior java',
    'tech lead',
    'ai integration',
    'senior software',
    'staff engineer',
    'principal engineer',
    'solutions architect',
    'backend lead',
    'platform engineer',
  ],

  tier2Titles: [
    'ml engineer',
    'machine learning',
    'applied ai',
    'genai',
    'gen ai',
    'ai engineer',
    'mlops',
  ],
};
